# -*- coding: utf-8 -*-
"""Internship project.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1EwHYcAgpH2sGX5JbtBxjwx2xCXFIecFE
"""

import pandas as pd
import numpy as np

df=pd.read_csv("student_performance_1000.csv")
df.head(10)

df.info()

df.columns

df.describe()

df.isnull().sum()

print(df.info())

df.tail()